CodeAssignment/CodeAssignment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeAssignment.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

CodeAssignment/CodeAssignment/Controllers/WebApiController.cs
using CodeAssignment.Infrastructure.Interfaces;
using CodeAssignment.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeAssignment.Controllers
{
    public class WebApiController : Controller
    {
        private readonly IExampleService<Result> service = null;

        public WebApiController()
        {
            service = Injector.injectorContainer.GetInstance<IExampleService<Result>>();
        }

        public ActionResult GetJsonData()
        {
            List<Result> model = service.GetItemList().ToList();
            return Json(new { results = model }, JsonRequestBehavior.AllowGet);
        }
    }
}

CodeAssignment/CodeAssignment/Views/Home/Index.cshtml
@using CodeAssignment.Infrastructure.Models
@model List<Result>
@{
    ViewBag.Title = "Please improve our work...";
}

<h1>Hello</h1>
<p>
    Can you convert this assignment to a Visual Studion project/solution, that runs on [F5]?<br />
    The json.txt should be replaced by a .Net api, that uses the repository pattern.<br /><br />
    Can you also extend the list of sales on this page? <br />
    And please put some effort in correcting and improving our scripts.<br /><br />
    We would like...
    <ul>
        <li>the id (i) of the sale before the name</li>
        <li>the city (c) and countryCode (cc) right aligned on the same line as the category</li>
        <li>clean readable code/scripts</li>
    </ul>

</p>
<hr />
<h2>Sales</h2>
<div id="list-of-sales"></div>


<script type="text/javascript">
    $(function () {
        GetSales('@Url.Action("GetJsonData", "WebApi")');
    });
</script>

CodeAssignment/CodeAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js" type="text/javascript"></script>

    <script src="~/Scripts/CodeAssignment.js"></script>

</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>